###LoGIN TO THE WeB
POST https://elearning-f7yg.onrender.com/api/v1/auth/login
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "123456789"
}





### register User

POST http://localhost:5000/api/v1/auth/register
Content-Type: application/json

{
  "name": "test User",
  "email": "test@gmail.com",
  "phoneNumber": "02839292992",
  "password": "123456789"

}

### Get My paid Classe
GET https://elearning-f7yg.onrender.com/api/v1/mypaid-class
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsInJvbGVJZCI6MywiaWF0IjoxNzQ5MTEyNTEzLCJleHAiOjE3NDkxMTM0MTN9.SmVIaGUhhxhZlJFGtQUi6x6b13MngGi0NvXIQxoW9c4



